trigger:
- main

pool:
  vmImage: 'windows-latest' # Update to 'ubuntu-latest' if running on Linux

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x' # Ensure Python 3.x is installed
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install robotframework
    pip install -r requirements.txt # Add this if you have specific dependencies
  displayName: 'Install Robot Framework and Dependencies'

- script: |
    robot --outputdir output tests/ # Adjust the path to your Robot Framework test folder
  displayName: 'Run Robot Framework Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'Robot'
    testResultsFiles: 'output/output.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish Robot Framework Test Results'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'output' # Adjust to match your output directory
    artifactName: 'RobotFrameworkResults'
    publishLocation: 'Container'
  displayName: 'Publish Test Artifacts'
