trigger:
- main

pool:
  vmImage: 'windows-latest' # Update to 'ubuntu-latest' if running on Linux

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Robot Framework and Dependencies'

- script: |
    robot -x Junit tests/notepad.robot  tests/rpa_notepad.robot 
  displayName: 'Run Robot Framework Tests'

- task: PublishTestResults@2
  continueOnError: true
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'Junit.xml'
    failTaskOnFailedTests: false
  displayName: 'Publish Robot Framework Test Results'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'report.html'
    ArtifactName: 'drop'
    publishLocation: 'Container'